# Generated by Django 2.1.1 on 2018-11-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0022_auto_20181116_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=10)),
                ('fixVersions', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('assignee', models.CharField(max_length=100, null=True)),
                ('iss_updated', models.DateTimeField()),
                ('iss_created', models.DateTimeField()),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jid', models.IntegerField()),
                ('icon_url', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.IntegerField()),
                ('key', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='issuetype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.IssueType'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='test_cases',
            field=models.ManyToManyField(to='testcases.TestCase'),
        ),
    ]
