# Generated by Django 2.1.1 on 2018-11-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('jira_key',)},
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='key',
            new_name='jira_key',
        ),
    ]
