# Generated by Django 2.1.1 on 2018-12-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20181130_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='fixVersions',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
