# Generated by Django 2.1.1 on 2018-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20181221_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetype',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
